In [14]:
import numpy as np

In [15]:
%load_ext numpy_html

The numpy_html extension is already loaded. To reload it, use:
  %reload_ext numpy_html


In [16]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [17]:
dataset = np.arange(1, 50).reshape(7, 7)
new_dataset = dataset+50
new_dataset

array([[51, 52, 53, 54, 55, 56, 57],
       [58, 59, 60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69, 70, 71],
       [72, 73, 74, 75, 76, 77, 78],
       [79, 80, 81, 82, 83, 84, 85],
       [86, 87, 88, 89, 90, 91, 92],
       [93, 94, 95, 96, 97, 98, 99]])

In [18]:
dataset_sum = np.sum(new_dataset)
dataset_sum

3675

In [19]:
odd = new_dataset % 2 != 0
odd_array = new_dataset[odd]
odd_sum = np.sum(odd_array)
odd_sum

1875

In [20]:
deviation = np.std(new_dataset)
deviation

14.142135623730951

In [21]:
total1 = np.sum(new_dataset, axis=1)
total1

array([378, 427, 476, 525, 574, 623, 672])

In [22]:
total0 = np.sum(new_dataset, axis=0)
total0

array([504, 511, 518, 525, 532, 539, 546])

In [23]:
print("rows:")
row_sums = []
for row in new_dataset:
    row_sum = sum(row)
    row_sums.append(row_sum)
for i, row_sum in enumerate(row_sums):
    print(row_sum)

print("columns:")
column_sums = [0] * len(new_dataset[0])
for row in new_dataset:
    for i, value in enumerate(row):
        column_sums[i] += value
for i, column_sum in enumerate(column_sums):
    print(column_sum)

rows:
378
427
476
525
574
623
672
columns:
504
511
518
525
532
539
546
