In [1]:
import numpy as np

In [2]:
%load_ext numpy_html

In [3]:
%%html
<style>
table {margin-top: 16pt;}
td {font-family: Arial, Helvetica, sans-serif !important; font-weight: 600; white-space: normal !important;}
tr:nth-child(even) {background: #b0d9eb !important; color: black}
tr:nth-child(odd) {background: #8fb1bf !important; color: black}
</style>

In [10]:
vector = np.array([5, 16, 9, 2, 19, 18, 11, 7])
max = np.argmax(vector)
max + 1 # 5th element, count starts from 0

5

In [4]:
data1 = np.arange(1, 50).reshape(7, 7)
data1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48, 49]])

In [5]:
data2 = np.random.randint(0, 6, 64).reshape(8, 8)
data2

array([[5, 4, 4, 2, 4, 5, 2, 4],
       [2, 0, 3, 5, 4, 2, 0, 4],
       [2, 0, 0, 4, 3, 1, 2, 3],
       [5, 5, 2, 4, 3, 2, 4, 5],
       [2, 4, 0, 0, 5, 2, 4, 2],
       [4, 1, 3, 1, 4, 2, 1, 1],
       [4, 5, 5, 4, 4, 3, 0, 4],
       [2, 2, 0, 2, 5, 0, 0, 2]])

In [6]:
data3 = np.random.randn(3)
data3 = np.random.randn(8, 8)
data3

array([[ 0.71455123, -0.46361474, -0.08334592,  0.44446074, -0.7667388 ,
        -0.19112384, -0.68650737,  1.75240056],
       [ 0.03333993,  0.83084918, -0.12757558,  0.99736085,  0.66516348,
         0.26301865,  2.91963938, -0.58327879],
       [ 0.6563964 ,  0.29460482, -1.24845916,  0.15635354, -0.73419805,
        -0.83781625, -1.19508825,  1.41706536],
       [-0.91087398,  2.23245939,  0.49332208, -0.02699008, -0.96553568,
         0.69886985, -0.0039526 ,  0.413488  ],
       [ 0.23180544, -0.39761461,  0.68800429,  0.52086944, -0.01903602,
        -0.10315741,  0.90465417,  0.60598497],
       [ 0.70241193, -1.11215713, -0.64643642, -0.13606361, -0.78267302,
        -1.1362975 ,  0.12796788,  0.03982478],
       [ 0.31811618,  0.49814957, -0.02653216,  1.11731043,  0.70115038,
         1.09407916,  0.64428539,  0.56734636],
       [ 0.25186283,  0.65589048,  0.45138352,  0.19468406, -0.53734453,
         1.66001666, -0.87371742, -0.47907684]])